export { default as Test } from './test'
export { default as Login } from './login'
export { default as Home } from './home'
export { default as Contents } from './contents'
export { default as Chats } from './chats'
export { default as Sign } from './sign'